/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecentGamesResponse } from '../../models/recent-games-response';

export interface GetRecentlyPlayedGames$Params {
}

export function getRecentlyPlayedGames(http: HttpClient, rootUrl: string, params?: GetRecentlyPlayedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RecentGamesResponse>>> {
  const rb = new RequestBuilder(rootUrl, getRecentlyPlayedGames.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RecentGamesResponse>>;
    })
  );
}

getRecentlyPlayedGames.PATH = '/profile/get-recent-games';
