/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserPublicResponse } from '../../models/user-public-response';

export interface GetUserPublic$Params {
  userId: number;
}

export function getUserPublic(http: HttpClient, rootUrl: string, params: GetUserPublic$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPublicResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserPublic.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserPublicResponse>;
    })
  );
}

getUserPublic.PATH = '/profile/user/{userId}';
