/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserLibraryResponse } from '../../models/user-library-response';

export interface GetLibraryGames$Params {
  query: string;
}

export function getLibraryGames(http: HttpClient, rootUrl: string, params: GetLibraryGames$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserLibraryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getLibraryGames.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserLibraryResponse>>;
    })
  );
}

getLibraryGames.PATH = '/profile/search-library-games';
