/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RecentGamesResponse } from '../../models/recent-games-response';

export interface GetUsersRecentlyPlayedGames$Params {
  userId: number;
}

export function getUsersRecentlyPlayedGames(http: HttpClient, rootUrl: string, params: GetUsersRecentlyPlayedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RecentGamesResponse>>> {
  const rb = new RequestBuilder(rootUrl, getUsersRecentlyPlayedGames.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RecentGamesResponse>>;
    })
  );
}

getUsersRecentlyPlayedGames.PATH = '/profile/get-recent-games/{userId}';
