/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatusResponse } from '../../models/status-response';

export interface GetUserStatus$Params {
}

export function getUserStatus(http: HttpClient, rootUrl: string, params?: GetUserStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<StatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatusResponse>;
    })
  );
}

getUserStatus.PATH = '/profile/status';
