/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminBanResponse {
  banReason?: string;
  bannedAt?: string;
  customMsg?: string;
  id?: number;
  reasonId?: number;
  reportId?: number;
  userId?: number;
}
