/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminSuspendedAccountsResponse {
  canceledAt?: string;
  createdAt?: string;
  daysSinceLastSuspension?: number;
  expiresAt?: string;
  messageFromAdmin?: string;
  reportId?: number;
  suspendedTimes?: number;
  suspensionId?: number;
  suspensionReason?: string;
  suspensionStatus?: 'ONGOING' | 'EXPIRED' | 'CANCELED';
  userId?: number;
  userName?: string;
}
