/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminSuspendedAccountsResponse {
  daysSinceLastSuspension?: number;
  expireAt?: string;
  messageFromAdmin?: string;
  reportId?: number;
  suspendedTimes?: number;
  suspensionId?: number;
  suspensionReason?: string;
  suspensionStatus?: 'ONGOING' | 'EXPIRED';
  userId?: number;
  userName?: string;
}
