/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminWarningResponse {
  adminMsg?: string;
  createdAt?: string;
  reportId?: number;
  userId?: number;
  warningId?: number;
}
