/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CountryResponse } from '../models/country-response';
export interface AdminUserResponse {
  accountLevel?: number;
  accountStatus?: 'ACTIVE' | 'BANNED' | 'DISABLED' | 'SUSPENDED' | 'DELETING' | 'DELETED';
  accountType?: 'ADULT' | 'CHILD';
  banReason?: string;
  bannedAt?: string;
  bio?: string;
  email?: string;
  firstName?: string;
  lastLogin?: string;
  lastModifiedAt?: string;
  lastName?: string;
  location?: CountryResponse;
  profileColor?: string;
  profilePicture?: string;
  registered?: string;
  role?: 'USER' | 'ADMIN';
  suspendedAt?: string;
  suspendedReason?: string;
  userId?: number;
  userName?: string;
}
