/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminBanResponse } from '../models/admin-ban-response';
import { AdminReportsResponse } from '../models/admin-reports-response';
import { AdminSuspendedAccountsResponse } from '../models/admin-suspended-accounts-response';
import { AdminWarningResponse } from '../models/admin-warning-response';
export interface AdminUserModerationResponse {
  accountStatus?: 'ACTIVE' | 'BANNED' | 'DISABLED' | 'SUSPENDED' | 'DELETING' | 'DELETED';
  banCount?: number;
  bans?: Array<AdminBanResponse>;
  registeredAt?: string;
  reportCount?: number;
  reports?: Array<AdminReportsResponse>;
  suspensionCount?: number;
  suspensions?: Array<AdminSuspendedAccountsResponse>;
  userId?: number;
  userName?: string;
  warningCount?: number;
  warnings?: Array<AdminWarningResponse>;
}
