/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUserResponse {
  accountStatus?: 'ACTIVE' | 'BANNED' | 'DISABLED';
  email?: string;
  firstName?: string;
  lastLogin?: string;
  lastName?: string;
  profilePicture?: Array<string>;
  registered?: string;
  role?: 'USER' | 'ADMIN';
  userId?: number;
  userName?: string;
}
