/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocationResponse } from '../models/location-response';
export interface AdminUserResponse {
  accountLevel?: number;
  accountStatus?: 'ACTIVE' | 'BANNED' | 'DISABLED' | 'SUSPENDED' | 'DELETING' | 'DELETED';
  accountType?: 'ADULT' | 'CHILD';
  bio?: string;
  email?: string;
  firstName?: string;
  lastLogin?: string;
  lastModifiedAt?: string;
  lastName?: string;
  location?: LocationResponse;
  profileColor?: string;
  profilePicture?: Array<string>;
  registered?: string;
  role?: 'USER' | 'ADMIN';
  userId?: number;
  userName?: string;
}
