/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminReportsResponse {
  createdAt?: string;
  reportId?: number;
  reportReason?: string;
  reportStatus?: 'NEW' | 'IN_REVIEW' | 'RESOLVED' | 'REJECTED';
  reportedUserEmail?: string;
  reportedUserId?: number;
  reportedUserName?: string;
  reporterId?: number;
  reporterUserName?: string;
}
