/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminReportsResponse {
  closedAt?: string;
  closedByReport?: number;
  createdAt?: string;
  moderationAction?: 'NONE' | 'WARNING' | 'SUSPEND' | 'BAN';
  reportId?: number;
  reportMsg?: string;
  reportReason?: string;
  reportStatus?: 'NEW' | 'IN_REVIEW' | 'RESOLVED' | 'REJECTED' | 'DISMISSED';
  reportedUserEmail?: string;
  reportedUserId?: number;
  reportedUserName?: string;
  reporterId?: number;
  reporterUserName?: string;
}
