/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BadgeResponse {
  description?: string;
  iconPath?: string;
  id?: number;
  name?: string;
}
