/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BadgeCategory } from '../models/badge-category';
export interface Badge {
  badgeCategory?: BadgeCategory;
  description?: string;
  iconPath?: string;
  id?: number;
  name?: string;
  xpReward?: number;
}
