/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Badge {
  badgeImage?: string;
  description?: string;
  id?: number;
  name?: string;
}
