/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BadgeCategory } from '../models/badge-category';
export interface BadgeRequest {
  badgeCategory?: BadgeCategory;
  description?: string;
  iconPath?: string;
  name?: string;
}
