/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameResponse } from '../models/game-response';
export interface CartResponse {
  cartId?: number;
  games?: Array<GameResponse>;
}
