/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommunitySettingsResponse {
  access?: string;
  description?: string;
  settingId?: number;
  settingName?: string;
  userId?: number;
}
