/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardReportResponse {
  createdAt?: string;
  id?: number;
  reason?: string;
  reportedUser?: string;
}
