/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardReportResponse } from '../models/dashboard-report-response';
import { User } from '../models/user';
export interface DashboardResponse {
  latestReports?: Array<DashboardReportResponse>;
  pendingReports?: number;
  recentUsers?: Array<User>;
  totalGames?: number;
  totalReviews?: number;
  totalUsers?: number;
}
