/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardReportResponse } from '../models/dashboard-report-response';
import { RecentUserResponse } from '../models/recent-user-response';
export interface DashboardResponse {
  latestReports?: Array<DashboardReportResponse>;
  pendingReports?: number;
  recentUsers?: Array<RecentUserResponse>;
  totalGames?: number;
  totalReviews?: number;
  totalUsers?: number;
}
