/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameResponseShort } from '../models/game-response-short';
import { LevelResponse } from '../models/level-response';
export interface FriendProfileResponse {
  currentlyPlaying?: GameResponseShort;
  level?: LevelResponse;
  profileColor?: string;
  status?: 'Online' | 'Playing' | 'Offline' | 'Away';
  userId?: number;
  userName?: string;
  userProfilePicture?: string;
}
