/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CountryResponse } from '../models/country-response';
import { LevelResponse } from '../models/level-response';
export interface FriendRequestResponse {
  country?: CountryResponse;
  createdAt?: string;
  level?: LevelResponse;
  profileColor?: string;
  status?: 'Online' | 'Playing' | 'Offline' | 'Away';
  userId?: number;
  userProfilePicture?: string;
  username?: string;
}
