/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LevelResponse } from '../models/level-response';
import { LocationResponse } from '../models/location-response';
export interface FriendRequestResponse {
  createdAt?: string;
  level?: LevelResponse;
  location?: LocationResponse;
  profileColor?: string;
  status?: 'ONLINE' | 'OFFLINE' | 'AWAY';
  userId?: number;
  userProfilePicture?: Array<string>;
  username?: string;
}
