/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenreResponse } from '../models/genre-response';
export interface GameResponse {
  description?: string;
  developer?: string;
  gameId?: number;
  genres?: Array<GenreResponse>;
  imageCover?: Array<string>;
  price?: number;
  publisher?: string;
  releaseYear?: string;
  title?: string;
}
