/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameUpdateRequest {
  ageRatingId: number;
  cpu: string;
  description: string;
  developer: string;
  discountPercent?: number | null;
  genresIds: Array<number>;
  gpu: string;
  languageIds: Array<number>;
  platformIds: Array<number>;
  price: number;
  publisher: string;
  ram: string;
  releaseYear: string;
  storage: string;
  subtitleIds: Array<number>;
  title: string;
}
