/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenreResponse } from '../models/genre-response';
import { LanguageResponse } from '../models/language-response';
import { PlatformResponse } from '../models/platform-response';
import { SubtitleResponse } from '../models/subtitle-response';
import { SystemRequirements } from '../models/system-requirements';
export interface GameResponse {
  description?: string;
  developer?: string;
  gameCoverImage?: Array<string>;
  gameId?: number;
  genres?: Array<GenreResponse>;
  languages?: Array<LanguageResponse>;
  platforms?: Array<PlatformResponse>;
  price?: number;
  publisher?: string;
  releaseYear?: string;
  subtitles?: Array<SubtitleResponse>;
  systemRequirements?: SystemRequirements;
  title?: string;
}
