/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Genre } from '../models/genre';
import { Language } from '../models/language';
import { Platform } from '../models/platform';
import { Subtitles } from '../models/subtitles';
export interface GameRequest {
  cpu: string;
  description: string;
  developer: string;
  gameId?: number;
  genres: Array<Genre>;
  gpu: string;
  languages: Array<Language>;
  os: string;
  platforms: Array<Platform>;
  price: number;
  publisher: string;
  ram: string;
  releaseYear: string;
  storage: string;
  subtitles: Array<Subtitles>;
  title: string;
}
