/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SystemRequirements } from '../models/system-requirements';
export interface Game {
  description?: string;
  developer?: string;
  dlc?: boolean;
  gameCoverImage?: string;
  id?: number;
  price?: number;
  publisher?: string;
  releaseYear?: string;
  systemRequirements?: SystemRequirements;
  title?: string;
}
