/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgeRating } from '../models/age-rating';
import { SystemRequirements } from '../models/system-requirements';
import { UserLibrary } from '../models/user-library';
export interface Game {
  ageRating?: AgeRating;
  description?: string;
  developer?: string;
  dlc?: boolean;
  gameCoverImage?: string;
  id?: number;
  price?: number;
  publisher?: string;
  releaseYear?: string;
  systemRequirements?: SystemRequirements;
  title?: string;
  users?: Array<UserLibrary>;
}
