/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameResponseShort {
  gameCoverImage?: Array<string>;
  gameId?: number;
  title?: string;
}
