/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Game {
  description?: string;
  developer?: string;
  dlc?: boolean;
  gameCoverImage?: string;
  id?: number;
  price?: number;
  publisher?: string;
  releaseYear?: string;
  title?: string;
}
