/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenreResponse } from '../models/genre-response';
export interface GamePreviewResponse {
  gameCoverImage?: Array<string>;
  gameId?: number;
  genres?: Array<GenreResponse>;
  price?: number;
  title?: string;
}
