/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameRequest {
  ageRatingId: number;
  cpu: string;
  description: string;
  developer: string;
  gameId?: number;
  gameUnitSize: string;
  genresIds: Array<number>;
  gpu: string;
  languageIds: Array<number>;
  platformIds: Array<number>;
  price: number;
  publisher: string;
  ram: number;
  releaseYear: string;
  storage: number;
  subtitleIds: Array<number>;
  title: string;
}
