/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GenreResponse } from '../models/genre-response';
export interface GamePreviewResponse {
  discountPercent?: number;
  discountPrice?: number;
  gameCoverImage?: string;
  gameId?: number;
  genres?: Array<GenreResponse>;
  hasDiscount?: boolean;
  inCart?: boolean;
  inWishList?: boolean;
  price?: number;
  title?: string;
}
