/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Level {
  id?: number;
  levelColor?: string;
  levelNumber?: number;
  requiredXp?: number;
}
