/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LevelResponse } from '../models/level-response';
export interface LevelProgressResponse {
  currentXp?: number;
  level?: LevelResponse;
  nextLevel?: number;
  requiredXp?: number;
}
