/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsResponse } from '../models/news-response';
export interface NewsOverviewResponse {
  hasUnseenNews?: boolean;
  news?: Array<NewsResponse>;
}
