/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsItemRequest } from '../models/news-item-request';
export interface NewsSectionRequest {
  newsItems: Array<NewsItemRequest>;
  newsType: 'ADDED' | 'IMPROVED' | 'FIXED' | 'SECURITY' | 'REMOVED';
}
