/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsSectionRequest } from '../models/news-section-request';
export interface NewsRequest {
  sections?: Array<NewsSectionRequest>;
  title: string;
  version: string;
}
