/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsSectionResponse } from '../models/news-section-response';
export interface NewsResponse {
  createdAt?: string;
  newsSections?: Array<NewsSectionResponse>;
  title?: string;
  version?: string;
}
