/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NewsItemResponse } from '../models/news-item-response';
export interface NewsSectionResponse {
  iconColor?: string;
  newsItems?: Array<NewsItemResponse>;
  newsType?: 'ADDED' | 'IMPROVED' | 'NOTES' | 'FIXED' | 'SECURITY' | 'REMOVED';
  newsTypeIcon?: string;
  newsTypeName?: string;
}
