/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OnboardRequest {
  genreIds?: Array<number>;
  mainPlatform: 'PC' | 'NINTENDO' | 'XBOX' | 'PS' | 'MOBILE';
  microphoneUsage: 'YES' | 'NO' | 'OPTIONAL';
}
