/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WishlistResponse } from '../models/wishlist-response';
export interface PageResponseWishlistResponse {
  content?: Array<WishlistResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
