/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FriendRequestResponse } from '../models/friend-request-response';
export interface PageResponseFriendRequestResponse {
  content?: Array<FriendRequestResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
