/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminReportsResponse } from '../models/admin-reports-response';
export interface PageResponseAdminReportsResponse {
  content?: Array<AdminReportsResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
