/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserCommunityResponse } from '../models/user-community-response';
export interface PageResponseUserCommunityResponse {
  content?: Array<UserCommunityResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
