/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminSuspendedAccountsResponse } from '../models/admin-suspended-accounts-response';
export interface PageResponseAdminSuspendedAccountsResponse {
  content?: Array<AdminSuspendedAccountsResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
