/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminUserResponse } from '../models/admin-user-response';
export interface PageResponseAdminUserResponse {
  content?: Array<AdminUserResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
