/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GamePreviewResponse } from '../models/game-preview-response';
export interface PageResponseGamePreviewResponse {
  content?: Array<GamePreviewResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
