/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface PasswordResetToken {
  expirationDateTime?: string;
  id?: number;
  token?: string;
  user?: User;
}
