/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecentUserResponse {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  username?: string;
}
