/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameResponseShort } from '../models/game-response-short';
export interface RecentGamesResponse {
  game?: GameResponseShort;
  lastPlayed?: string;
  playTime?: number;
}
