/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  createdAt?: string;
  id?: number;
  lastModifiedAt?: string;
  name?: string;
}
