/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoreSettingsResponse {
  description?: string;
  disabled?: boolean;
  pegiRatingName?: string;
  settingId?: number;
  userId?: number;
}
