/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
export interface Subtitles {
  games?: Array<Game>;
  id?: number;
  name?: string;
}
