/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SuspendAccountRequest {
  customMessage: string;
  expiresAt: string;
  suspendReason: number;
}
