/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SystemRequirements {
  cpu?: string;
  gameUnitSize?: 'MB' | 'GB' | 'TB';
  gpu?: string;
  id?: number;
  ram?: number;
  storage?: number;
}
