/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SystemRequirements {
  cpu?: string;
  gpu?: string;
  id?: number;
  os?: string;
  ram?: string;
  storage?: string;
}
