/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateCommunitySettingsRequest {
  access: 'EVERYONE' | 'FRIENDS' | 'NO_ONE';
  settingId: number;
}
