/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocationResponse } from '../models/location-response';
export interface UserCommunityResponse {
  friendRequestReceived?: boolean;
  friendRequestSent?: boolean;
  friendsCount?: number;
  isFriend?: boolean;
  joinedDate?: string;
  libraryCount?: number;
  location?: LocationResponse;
  profileColor?: string;
  reviewsCount?: number;
  status?: 'ONLINE' | 'OFFLINE' | 'AWAY';
  userId?: number;
  userProfilePicture?: string;
  username?: string;
}
