/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdateRequest {
  bio?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  location?: 'SLOVAKIA' | 'CZECH_REPUBLIC' | 'POLAND' | 'HUNGARY' | 'USA';
  userProfilePicture?: Array<string>;
  username?: string;
}
