/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CountryResponse } from '../models/country-response';
import { GameResponseShort } from '../models/game-response-short';
import { MicrophoneUsageResponse } from '../models/microphone-usage-response';
import { PlatformResponse } from '../models/platform-response';
export interface UserCommunityResponse {
  country?: CountryResponse;
  currentlyPlaying?: GameResponseShort;
  friendRequestReceived?: boolean;
  friendRequestSent?: boolean;
  friendsCount?: number;
  isFriend?: boolean;
  joinedDate?: string;
  libraryCount?: number;
  mainPlatform?: PlatformResponse;
  microphoneUsage?: MicrophoneUsageResponse;
  profileColor?: string;
  reviewsCount?: number;
  status?: 'Online' | 'Playing' | 'Offline' | 'Away';
  userId?: number;
  userProfilePicture?: string;
  username?: string;
}
