/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BadgeResponse } from '../models/badge-response';
import { CardColorResponse } from '../models/card-color-response';
import { GameResponseShort } from '../models/game-response-short';
import { GenreResponse } from '../models/genre-response';
import { LevelResponse } from '../models/level-response';
import { LocationResponse } from '../models/location-response';
export interface UserPublicResponse {
  accountStatus?: 'ACTIVE' | 'BANNED' | 'DISABLED' | 'SUSPENDED' | 'DELETING' | 'DELETED';
  badges?: Array<BadgeResponse>;
  bannerImage?: string;
  bannerType?: string;
  bio?: string;
  cardColor?: CardColorResponse;
  favoriteGames?: Array<GameResponseShort>;
  favoriteGenres?: Array<GenreResponse>;
  friendRequestReceived?: boolean;
  friendRequestSent?: boolean;
  friendsCount?: number;
  isFriend?: boolean;
  joinedDate?: string;
  level?: LevelResponse;
  libraryCount?: number;
  location?: LocationResponse;
  playRecently?: Array<GameResponseShort>;
  playTime?: number;
  predefinedBannerPath?: string;
  profileColor?: string;
  recommendedGames?: Array<GameResponseShort>;
  reviews?: number;
  status?: 'ONLINE' | 'OFFLINE' | 'AWAY';
  userId?: number;
  userProfilePicture?: string;
  username?: string;
  wishlistCount?: number;
}
