/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BadgeResponse } from '../models/badge-response';
import { GameResponseShort } from '../models/game-response-short';
import { GenreResponse } from '../models/genre-response';
import { LocationResponse } from '../models/location-response';
export interface UserPrivateResponse {
  badges?: Array<BadgeResponse>;
  bannerImage?: Array<string>;
  bannerType?: string;
  bio?: string;
  email?: string;
  favoriteGames?: Array<GameResponseShort>;
  favoriteGenres?: Array<GenreResponse>;
  firstName?: string;
  joinedDate?: string;
  lastName?: string;
  libraryCount?: number;
  location?: LocationResponse;
  playRecently?: Array<GameResponseShort>;
  predefinedBannerPath?: string;
  profileColor?: string;
  recommendedGames?: Array<GameResponseShort>;
  status?: 'ONLINE' | 'OFFLINE' | 'AWAY';
  userId?: number;
  userProfilePicture?: Array<string>;
  username?: string;
  wishlistCount?: number;
}
