/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Badge } from '../models/badge';
import { CardColor } from '../models/card-color';
import { Game } from '../models/game';
import { Genre } from '../models/genre';
import { GrantedAuthority } from '../models/granted-authority';
import { Level } from '../models/level';
import { PasswordResetToken } from '../models/password-reset-token';
import { Role } from '../models/role';
import { UserLibrary } from '../models/user-library';
export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  accountType?: 'ADULT' | 'CHILD';
  authorities?: Array<GrantedAuthority>;
  badges?: Array<Badge>;
  banned?: boolean;
  banner?: string;
  bannerType?: string;
  bio?: string;
  cardColor?: CardColor;
  createdAt?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  favoriteGames?: Array<Game>;
  favoriteGenres?: Array<Genre>;
  firstName?: string;
  friends?: Array<User>;
  fullName?: string;
  id?: number;
  lastModifiedAt?: string;
  lastName?: string;
  level?: Level;
  library?: Array<Game>;
  location?: 'SK' | 'CZ' | 'PL' | 'HU' | 'US' | 'UNKNOWN';
  name?: string;
  parentEmail?: string;
  password?: string;
  passwordResetTokens?: Array<PasswordResetToken>;
  playRecently?: Array<Game>;
  profileColor?: string;
  recommendationGames?: Array<Game>;
  roles?: Array<Role>;
  status?: 'ONLINE' | 'OFFLINE' | 'AWAY';
  userLibrary?: Array<UserLibrary>;
  userProfilePicture?: string;
  username?: string;
  wishlist?: Array<Game>;
  xp?: number;
}
