/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgeRatingResponse } from '../models/age-rating-response';
import { GenreResponse } from '../models/genre-response';
export interface UserLibraryResponse {
  ageRating?: AgeRatingResponse;
  currentlyPlaying?: boolean;
  description?: string;
  developer?: string;
  favorite?: boolean;
  gameCoverImage?: string;
  gameId?: number;
  genres?: Array<GenreResponse>;
  installed?: boolean;
  playtimeMinutes?: number;
  publisher?: string;
  releaseYear?: string;
  title?: string;
}
