/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserNotificationsResponse {
  cartCount?: number | null;
  suspendedCount?: number | null;
  warningCount?: number | null;
}
