/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BadgeResponse } from '../models/badge-response';
import { CardColorResponse } from '../models/card-color-response';
import { FriendProfileResponse } from '../models/friend-profile-response';
import { GameResponseShort } from '../models/game-response-short';
import { GenreResponse } from '../models/genre-response';
import { LevelResponse } from '../models/level-response';
import { LocationResponse } from '../models/location-response';
import { RecentGamesResponse } from '../models/recent-games-response';
import { UserLibraryResponse } from '../models/user-library-response';
import { WishlistResponse } from '../models/wishlist-response';
export interface UserPrivateResponse {
  badges?: Array<BadgeResponse>;
  bannerImage?: string;
  bannerType?: string;
  bio?: string;
  cardColor?: CardColorResponse;
  currentlyPlaying?: GameResponseShort;
  email?: string;
  favoriteGame?: UserLibraryResponse;
  favoriteGenres?: Array<GenreResponse>;
  firstName?: string;
  friendReqCount?: number;
  friends?: Array<FriendProfileResponse>;
  friendsCount?: number;
  joinedDate?: string;
  lastName?: string;
  level?: LevelResponse;
  libraryCount?: number;
  location?: LocationResponse;
  playTime?: number;
  predefinedBannerPath?: string;
  profileColor?: string;
  recentGamesResponse?: Array<RecentGamesResponse>;
  recommendedGames?: Array<GameResponseShort>;
  reviews?: number;
  status?: 'Online' | 'Playing' | 'Offline' | 'Away';
  userId?: number;
  userProfilePicture?: string;
  username?: string;
  wishlist?: WishlistResponse;
  wishlistCount?: number;
}
