/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserLibraryResponse {
  currentlyPlaying?: boolean;
  favorite?: boolean;
  gameCoverImage?: string;
  gameId?: number;
  installed?: boolean;
  lastPlayed?: string;
  playtimeMinutes?: number;
  title?: string;
}
