/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommunitySettingsResponse } from '../models/community-settings-response';
import { PrivacySettingsResponse } from '../models/privacy-settings-response';
import { StoreSettingsResponse } from '../models/store-settings-response';
export interface UserSettingsResponse {
  communitySettingsResponse?: Array<CommunitySettingsResponse>;
  privacySettingsResponse?: Array<PrivacySettingsResponse>;
  storeSettingsResponse?: Array<StoreSettingsResponse>;
}
