/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { User } from '../models/user';
import { UserGameId } from '../models/user-game-id';
export interface UserLibrary {
  createdAt?: string;
  favorite?: boolean;
  game?: Game;
  id?: UserGameId;
  installed?: boolean;
  lastPlayed?: string;
  playtimeMinutes?: number;
  user?: User;
}
