/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserUpdateRequest {
  bio?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  location?: 'SK' | 'CZ' | 'PL' | 'HU' | 'US';
  username?: string;
}
