/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GamePreviewResponse } from '../models/game-preview-response';
export interface WishlistResponse {
  addedAt?: string;
  game?: GamePreviewResponse;
}
