/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { User } from '../models/user';
import { UserWishlistId } from '../models/user-wishlist-id';
export interface Wishlist {
  addedAt?: string;
  game?: Game;
  id?: UserWishlistId;
  user?: User;
}
