/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserSettingsResponse } from '../../models/user-settings-response';

export interface GetUserSettings$Params {
}

export function getUserSettings(http: HttpClient, rootUrl: string, params?: GetUserSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserSettingsResponse>;
    })
  );
}

getUserSettings.PATH = '/settings/settings';
