/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DashboardResponse } from '../models/dashboard-response';
import { loadDashboardData } from '../fn/admin-controller/load-dashboard-data';
import { LoadDashboardData$Params } from '../fn/admin-controller/load-dashboard-data';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `loadDashboardData()` */
  static readonly LoadDashboardDataPath = '/admin/dashboard';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `loadDashboardData()` instead.
   *
   * This method doesn't expect any request body.
   */
  loadDashboardData$Response(params?: LoadDashboardData$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardResponse>> {
    return loadDashboardData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `loadDashboardData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  loadDashboardData(params?: LoadDashboardData$Params, context?: HttpContext): Observable<DashboardResponse> {
    return this.loadDashboardData$Response(params, context).pipe(
      map((r: StrictHttpResponse<DashboardResponse>): DashboardResponse => r.body)
    );
  }

}
