/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccountStatusResponse } from '../models/account-status-response';
import { addGame } from '../fn/admin-controller/add-game';
import { AddGame$Params } from '../fn/admin-controller/add-game';
import { AdminUserResponse } from '../models/admin-user-response';
import { banUser } from '../fn/admin-controller/ban-user';
import { BanUser$Params } from '../fn/admin-controller/ban-user';
import { changeRole } from '../fn/admin-controller/change-role';
import { ChangeRole$Params } from '../fn/admin-controller/change-role';
import { DashboardResponse } from '../models/dashboard-response';
import { deleteGame } from '../fn/admin-controller/delete-game';
import { DeleteGame$Params } from '../fn/admin-controller/delete-game';
import { GameResponse } from '../models/game-response';
import { getAllAccountStatuses } from '../fn/admin-controller/get-all-account-statuses';
import { GetAllAccountStatuses$Params } from '../fn/admin-controller/get-all-account-statuses';
import { getAllGames } from '../fn/admin-controller/get-all-games';
import { GetAllGames$Params } from '../fn/admin-controller/get-all-games';
import { getAllRoles } from '../fn/admin-controller/get-all-roles';
import { GetAllRoles$Params } from '../fn/admin-controller/get-all-roles';
import { getAllUsers } from '../fn/admin-controller/get-all-users';
import { GetAllUsers$Params } from '../fn/admin-controller/get-all-users';
import { getGameInfo } from '../fn/admin-controller/get-game-info';
import { GetGameInfo$Params } from '../fn/admin-controller/get-game-info';
import { getUserInfo } from '../fn/admin-controller/get-user-info';
import { GetUserInfo$Params } from '../fn/admin-controller/get-user-info';
import { loadDashboardData } from '../fn/admin-controller/load-dashboard-data';
import { LoadDashboardData$Params } from '../fn/admin-controller/load-dashboard-data';
import { PageResponseAdminUserResponse } from '../models/page-response-admin-user-response';
import { PageResponseGamePreviewResponse } from '../models/page-response-game-preview-response';
import { RoleResponse } from '../models/role-response';
import { unBanUser } from '../fn/admin-controller/un-ban-user';
import { UnBanUser$Params } from '../fn/admin-controller/un-ban-user';
import { updateGame } from '../fn/admin-controller/update-game';
import { UpdateGame$Params } from '../fn/admin-controller/update-game';
import { uploadGameCoverImage } from '../fn/admin-controller/upload-game-cover-image';
import { UploadGameCoverImage$Params } from '../fn/admin-controller/upload-game-cover-image';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `unBanUser()` */
  static readonly UnBanUserPath = '/admin/unban/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unBanUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  unBanUser$Response(params: UnBanUser$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return unBanUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unBanUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unBanUser(params: UnBanUser$Params, context?: HttpContext): Observable<number> {
    return this.unBanUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateGame()` */
  static readonly UpdateGamePath = '/admin/edit-game/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateGame()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateGame$Response(params: UpdateGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateGame$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateGame(params: UpdateGame$Params, context?: HttpContext): Observable<number> {
    return this.updateGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `changeRole()` */
  static readonly ChangeRolePath = '/admin/change-role/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeRole$Response(params: ChangeRole$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return changeRole(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeRole(params: ChangeRole$Params, context?: HttpContext): Observable<number> {
    return this.changeRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `banUser()` */
  static readonly BanUserPath = '/admin/ban/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `banUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  banUser$Response(params: BanUser$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return banUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `banUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  banUser(params: BanUser$Params, context?: HttpContext): Observable<number> {
    return this.banUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `uploadGameCoverImage()` */
  static readonly UploadGameCoverImagePath = '/admin/cover/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadGameCoverImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameCoverImage$Response(params: UploadGameCoverImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadGameCoverImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadGameCoverImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameCoverImage(params: UploadGameCoverImage$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadGameCoverImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `addGame()` */
  static readonly AddGamePath = '/admin/add-game';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addGame()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addGame$Response(params: AddGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addGame$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addGame(params: AddGame$Params, context?: HttpContext): Observable<number> {
    return this.addGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAllUsers()` */
  static readonly GetAllUsersPath = '/admin/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsers$Response(params?: GetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAdminUserResponse>> {
    return getAllUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUsers(params?: GetAllUsers$Params, context?: HttpContext): Observable<PageResponseAdminUserResponse> {
    return this.getAllUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseAdminUserResponse>): PageResponseAdminUserResponse => r.body)
    );
  }

  /** Path part for operation `getUserInfo()` */
  static readonly GetUserInfoPath = '/admin/user/info/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserInfo$Response(params: GetUserInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminUserResponse>> {
    return getUserInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserInfo(params: GetUserInfo$Params, context?: HttpContext): Observable<AdminUserResponse> {
    return this.getUserInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<AdminUserResponse>): AdminUserResponse => r.body)
    );
  }

  /** Path part for operation `getAllRoles()` */
  static readonly GetAllRolesPath = '/admin/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles$Response(params?: GetAllRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleResponse>>> {
    return getAllRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles(params?: GetAllRoles$Params, context?: HttpContext): Observable<Array<RoleResponse>> {
    return this.getAllRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoleResponse>>): Array<RoleResponse> => r.body)
    );
  }

  /** Path part for operation `getGameInfo()` */
  static readonly GetGameInfoPath = '/admin/game/info/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGameInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGameInfo$Response(params: GetGameInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<GameResponse>> {
    return getGameInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGameInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGameInfo(params: GetGameInfo$Params, context?: HttpContext): Observable<GameResponse> {
    return this.getGameInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<GameResponse>): GameResponse => r.body)
    );
  }

  /** Path part for operation `loadDashboardData()` */
  static readonly LoadDashboardDataPath = '/admin/dashboard';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `loadDashboardData()` instead.
   *
   * This method doesn't expect any request body.
   */
  loadDashboardData$Response(params?: LoadDashboardData$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardResponse>> {
    return loadDashboardData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `loadDashboardData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  loadDashboardData(params?: LoadDashboardData$Params, context?: HttpContext): Observable<DashboardResponse> {
    return this.loadDashboardData$Response(params, context).pipe(
      map((r: StrictHttpResponse<DashboardResponse>): DashboardResponse => r.body)
    );
  }

  /** Path part for operation `getAllGames()` */
  static readonly GetAllGamesPath = '/admin/admin/games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllGames$Response(params?: GetAllGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGamePreviewResponse>> {
    return getAllGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllGames(params?: GetAllGames$Params, context?: HttpContext): Observable<PageResponseGamePreviewResponse> {
    return this.getAllGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGamePreviewResponse>): PageResponseGamePreviewResponse => r.body)
    );
  }

  /** Path part for operation `getAllAccountStatuses()` */
  static readonly GetAllAccountStatusesPath = '/admin/account-statuses';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAccountStatuses()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccountStatuses$Response(params?: GetAllAccountStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountStatusResponse>>> {
    return getAllAccountStatuses(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAccountStatuses$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAccountStatuses(params?: GetAllAccountStatuses$Params, context?: HttpContext): Observable<Array<AccountStatusResponse>> {
    return this.getAllAccountStatuses$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AccountStatusResponse>>): Array<AccountStatusResponse> => r.body)
    );
  }

  /** Path part for operation `deleteGame()` */
  static readonly DeleteGamePath = '/admin/game/delete/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteGame$Response(params: DeleteGame$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteGame(params: DeleteGame$Params, context?: HttpContext): Observable<void> {
    return this.deleteGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
