/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addBadge } from '../fn/badge-controller/add-badge';
import { AddBadge$Params } from '../fn/badge-controller/add-badge';
import { addCategory } from '../fn/badge-controller/add-category';
import { AddCategory$Params } from '../fn/badge-controller/add-category';
import { BadgeResponse } from '../models/badge-response';
import { getAllUserBadges } from '../fn/badge-controller/get-all-user-badges';
import { GetAllUserBadges$Params } from '../fn/badge-controller/get-all-user-badges';

@Injectable({ providedIn: 'root' })
export class BadgeControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addCategory()` */
  static readonly AddCategoryPath = '/badge/add-category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCategory$Response(params: AddCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addCategory(params: AddCategory$Params, context?: HttpContext): Observable<number> {
    return this.addCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `addBadge()` */
  static readonly AddBadgePath = '/badge/add-badge';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addBadge()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addBadge$Response(params: AddBadge$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addBadge(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addBadge$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addBadge(params: AddBadge$Params, context?: HttpContext): Observable<number> {
    return this.addBadge$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAllUserBadges()` */
  static readonly GetAllUserBadgesPath = '/badge/all-badges';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllUserBadges()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUserBadges$Response(params?: GetAllUserBadges$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BadgeResponse>>> {
    return getAllUserBadges(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllUserBadges$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllUserBadges(params?: GetAllUserBadges$Params, context?: HttpContext): Observable<Array<BadgeResponse>> {
    return this.getAllUserBadges$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BadgeResponse>>): Array<BadgeResponse> => r.body)
    );
  }

}
