/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CardColorResponse } from '../models/card-color-response';
import { getColors } from '../fn/card-color-controller/get-colors';
import { GetColors$Params } from '../fn/card-color-controller/get-colors';

@Injectable({ providedIn: 'root' })
export class CardColorControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getColors()` */
  static readonly GetColorsPath = '/color/all-colors';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getColors()` instead.
   *
   * This method doesn't expect any request body.
   */
  getColors$Response(params?: GetColors$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CardColorResponse>>> {
    return getColors(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getColors$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getColors(params?: GetColors$Params, context?: HttpContext): Observable<Array<CardColorResponse>> {
    return this.getColors$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CardColorResponse>>): Array<CardColorResponse> => r.body)
    );
  }

}
