/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addGameToCart } from '../fn/cart-controller/add-game-to-cart';
import { AddGameToCart$Params } from '../fn/cart-controller/add-game-to-cart';
import { CartResponse } from '../models/cart-response';
import { getCart } from '../fn/cart-controller/get-cart';
import { GetCart$Params } from '../fn/cart-controller/get-cart';
import { removeFromCart } from '../fn/cart-controller/remove-from-cart';
import { RemoveFromCart$Params } from '../fn/cart-controller/remove-from-cart';

@Injectable({ providedIn: 'root' })
export class CartControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addGameToCart()` */
  static readonly AddGameToCartPath = '/cart/add-to-cart';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addGameToCart()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addGameToCart$Response(params: AddGameToCart$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addGameToCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addGameToCart$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addGameToCart(params: AddGameToCart$Params, context?: HttpContext): Observable<number> {
    return this.addGameToCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getCart()` */
  static readonly GetCartPath = '/cart/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCart$Response(params?: GetCart$Params, context?: HttpContext): Observable<StrictHttpResponse<CartResponse>> {
    return getCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCart(params?: GetCart$Params, context?: HttpContext): Observable<CartResponse> {
    return this.getCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<CartResponse>): CartResponse => r.body)
    );
  }

  /** Path part for operation `removeFromCart()` */
  static readonly RemoveFromCartPath = '/cart/remove-from-cart/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeFromCart()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFromCart$Response(params: RemoveFromCart$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return removeFromCart(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeFromCart$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeFromCart(params: RemoveFromCart$Params, context?: HttpContext): Observable<number> {
    return this.removeFromCart$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
