/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FlagsResponse } from '../models/flags-response';
import { getAllCommunityFlags } from '../fn/flags-controller/get-all-community-flags';
import { GetAllCommunityFlags$Params } from '../fn/flags-controller/get-all-community-flags';
import { getAllStoreFlags } from '../fn/flags-controller/get-all-store-flags';
import { GetAllStoreFlags$Params } from '../fn/flags-controller/get-all-store-flags';
import { StoreFlagsResponse } from '../models/store-flags-response';

@Injectable({ providedIn: 'root' })
export class FlagsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllStoreFlags()` */
  static readonly GetAllStoreFlagsPath = '/flags/get/store/flags';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllStoreFlags()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStoreFlags$Response(params?: GetAllStoreFlags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<StoreFlagsResponse>>> {
    return getAllStoreFlags(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllStoreFlags$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllStoreFlags(params?: GetAllStoreFlags$Params, context?: HttpContext): Observable<Array<StoreFlagsResponse>> {
    return this.getAllStoreFlags$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<StoreFlagsResponse>>): Array<StoreFlagsResponse> => r.body)
    );
  }

  /** Path part for operation `getAllCommunityFlags()` */
  static readonly GetAllCommunityFlagsPath = '/flags/get/community/flags';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCommunityFlags()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCommunityFlags$Response(params?: GetAllCommunityFlags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlagsResponse>>> {
    return getAllCommunityFlags(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCommunityFlags$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCommunityFlags(params?: GetAllCommunityFlags$Params, context?: HttpContext): Observable<Array<FlagsResponse>> {
    return this.getAllCommunityFlags$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlagsResponse>>): Array<FlagsResponse> => r.body)
    );
  }

}
