/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addGame } from '../fn/game-controller/add-game';
import { AddGame$Params } from '../fn/game-controller/add-game';
import { buyGame } from '../fn/game-controller/buy-game';
import { BuyGame$Params } from '../fn/game-controller/buy-game';
import { checkGameOwned } from '../fn/game-controller/check-game-owned';
import { CheckGameOwned$Params } from '../fn/game-controller/check-game-owned';
import { findAllGames } from '../fn/game-controller/find-all-games';
import { FindAllGames$Params } from '../fn/game-controller/find-all-games';
import { GameResponse } from '../models/game-response';
import { getGameById } from '../fn/game-controller/get-game-by-id';
import { GetGameById$Params } from '../fn/game-controller/get-game-by-id';
import { PageResponseGameResponse } from '../models/page-response-game-response';
import { uploadGameCoverImage } from '../fn/game-controller/upload-game-cover-image';
import { UploadGameCoverImage$Params } from '../fn/game-controller/upload-game-cover-image';

@Injectable({ providedIn: 'root' })
export class GameControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `uploadGameCoverImage()` */
  static readonly UploadGameCoverImagePath = '/store/cover/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadGameCoverImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameCoverImage$Response(params: UploadGameCoverImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadGameCoverImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadGameCoverImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadGameCoverImage(params: UploadGameCoverImage$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadGameCoverImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `buyGame()` */
  static readonly BuyGamePath = '/store/buy/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buyGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  buyGame$Response(params: BuyGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return buyGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buyGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buyGame(params: BuyGame$Params, context?: HttpContext): Observable<number> {
    return this.buyGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `addGame()` */
  static readonly AddGamePath = '/store/add-game';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addGame()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addGame$Response(params: AddGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addGame$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addGame(params: AddGame$Params, context?: HttpContext): Observable<number> {
    return this.addGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getGameById()` */
  static readonly GetGameByIdPath = '/store/game/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGameById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGameById$Response(params: GetGameById$Params, context?: HttpContext): Observable<StrictHttpResponse<GameResponse>> {
    return getGameById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGameById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGameById(params: GetGameById$Params, context?: HttpContext): Observable<GameResponse> {
    return this.getGameById$Response(params, context).pipe(
      map((r: StrictHttpResponse<GameResponse>): GameResponse => r.body)
    );
  }

  /** Path part for operation `checkGameOwned()` */
  static readonly CheckGameOwnedPath = '/store/check/game/{gameId}/owned/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkGameOwned()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkGameOwned$Response(params: CheckGameOwned$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkGameOwned(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkGameOwned$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkGameOwned(params: CheckGameOwned$Params, context?: HttpContext): Observable<boolean> {
    return this.checkGameOwned$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `findAllGames()` */
  static readonly FindAllGamesPath = '/store/all-games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames$Response(params?: FindAllGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return findAllGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames(params?: FindAllGames$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.findAllGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

}
