/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getLibrary } from '../fn/library-controller/get-library';
import { GetLibrary$Params } from '../fn/library-controller/get-library';
import { PageResponseGameResponse } from '../models/page-response-game-response';

@Injectable({ providedIn: 'root' })
export class LibraryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getLibrary()` */
  static readonly GetLibraryPath = '/library/library';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLibrary()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLibrary$Response(params?: GetLibrary$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return getLibrary(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLibrary$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLibrary(params?: GetLibrary$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.getLibrary$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

}
