/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getLocations } from '../fn/location-controller/get-locations';
import { GetLocations$Params } from '../fn/location-controller/get-locations';
import { LocationResponse } from '../models/location-response';

@Injectable({ providedIn: 'root' })
export class LocationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getLocations()` */
  static readonly GetLocationsPath = '/location/locations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLocations()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLocations$Response(params?: GetLocations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationResponse>>> {
    return getLocations(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLocations$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLocations(params?: GetLocations$Params, context?: HttpContext): Observable<Array<LocationResponse>> {
    return this.getLocations$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LocationResponse>>): Array<LocationResponse> => r.body)
    );
  }

}
