/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CommunityGuidelinesResponse } from '../models/community-guidelines-response';
import { getAllCommunityGuidelines } from '../fn/report-controller/get-all-community-guidelines';
import { GetAllCommunityGuidelines$Params } from '../fn/report-controller/get-all-community-guidelines';
import { reportUser } from '../fn/report-controller/report-user';
import { ReportUser$Params } from '../fn/report-controller/report-user';

@Injectable({ providedIn: 'root' })
export class ReportControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `reportUser()` */
  static readonly ReportUserPath = '/report/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `reportUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportUser$Response(params: ReportUser$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return reportUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `reportUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  reportUser(params: ReportUser$Params, context?: HttpContext): Observable<number> {
    return this.reportUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getAllCommunityGuidelines()` */
  static readonly GetAllCommunityGuidelinesPath = '/report/get/community-guidelines';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCommunityGuidelines()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCommunityGuidelines$Response(params?: GetAllCommunityGuidelines$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommunityGuidelinesResponse>>> {
    return getAllCommunityGuidelines(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCommunityGuidelines$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCommunityGuidelines(params?: GetAllCommunityGuidelines$Params, context?: HttpContext): Observable<Array<CommunityGuidelinesResponse>> {
    return this.getAllCommunityGuidelines$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CommunityGuidelinesResponse>>): Array<CommunityGuidelinesResponse> => r.body)
    );
  }

}
