/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { updateUserSettings } from '../fn/settings-controller/update-user-settings';
import { UpdateUserSettings$Params } from '../fn/settings-controller/update-user-settings';

@Injectable({ providedIn: 'root' })
export class SettingsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateUserSettings()` */
  static readonly UpdateUserSettingsPath = '/settings/update/user-settings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUserSettings()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserSettings$Response(params: UpdateUserSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateUserSettings(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUserSettings$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserSettings(params: UpdateUserSettings$Params, context?: HttpContext): Observable<number> {
    return this.updateUserSettings$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

}
