/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addGameToWishlist } from '../fn/store-controller/add-game-to-wishlist';
import { AddGameToWishlist$Params } from '../fn/store-controller/add-game-to-wishlist';
import { AgeRatingResponse } from '../models/age-rating-response';
import { buyGame } from '../fn/store-controller/buy-game';
import { BuyGame$Params } from '../fn/store-controller/buy-game';
import { checkGameInWishlist } from '../fn/store-controller/check-game-in-wishlist';
import { CheckGameInWishlist$Params } from '../fn/store-controller/check-game-in-wishlist';
import { checkGameOwned } from '../fn/store-controller/check-game-owned';
import { CheckGameOwned$Params } from '../fn/store-controller/check-game-owned';
import { findAllGames } from '../fn/store-controller/find-all-games';
import { FindAllGames$Params } from '../fn/store-controller/find-all-games';
import { GameResponse } from '../models/game-response';
import { GenreResponse } from '../models/genre-response';
import { getAgeRating } from '../fn/store-controller/get-age-rating';
import { GetAgeRating$Params } from '../fn/store-controller/get-age-rating';
import { getAllGenres } from '../fn/store-controller/get-all-genres';
import { GetAllGenres$Params } from '../fn/store-controller/get-all-genres';
import { getAllPlatforms } from '../fn/store-controller/get-all-platforms';
import { GetAllPlatforms$Params } from '../fn/store-controller/get-all-platforms';
import { getGameById } from '../fn/store-controller/get-game-by-id';
import { GetGameById$Params } from '../fn/store-controller/get-game-by-id';
import { getLanguages } from '../fn/store-controller/get-languages';
import { GetLanguages$Params } from '../fn/store-controller/get-languages';
import { getSubtitles } from '../fn/store-controller/get-subtitles';
import { GetSubtitles$Params } from '../fn/store-controller/get-subtitles';
import { LanguageResponse } from '../models/language-response';
import { PageResponseGameResponse } from '../models/page-response-game-response';
import { PlatformResponse } from '../models/platform-response';
import { removeGameFromWishlist } from '../fn/store-controller/remove-game-from-wishlist';
import { RemoveGameFromWishlist$Params } from '../fn/store-controller/remove-game-from-wishlist';
import { SubtitleResponse } from '../models/subtitle-response';

@Injectable({ providedIn: 'root' })
export class StoreControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `removeGameFromWishlist()` */
  static readonly RemoveGameFromWishlistPath = '/store/delete/wishlist/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeGameFromWishlist()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeGameFromWishlist$Response(params: RemoveGameFromWishlist$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return removeGameFromWishlist(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeGameFromWishlist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeGameFromWishlist(params: RemoveGameFromWishlist$Params, context?: HttpContext): Observable<number> {
    return this.removeGameFromWishlist$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `buyGame()` */
  static readonly BuyGamePath = '/store/buy/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `buyGame()` instead.
   *
   * This method doesn't expect any request body.
   */
  buyGame$Response(params: BuyGame$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return buyGame(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `buyGame$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  buyGame(params: BuyGame$Params, context?: HttpContext): Observable<number> {
    return this.buyGame$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `addGameToWishlist()` */
  static readonly AddGameToWishlistPath = '/store/add/wishlist/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addGameToWishlist()` instead.
   *
   * This method doesn't expect any request body.
   */
  addGameToWishlist$Response(params: AddGameToWishlist$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return addGameToWishlist(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addGameToWishlist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addGameToWishlist(params: AddGameToWishlist$Params, context?: HttpContext): Observable<number> {
    return this.addGameToWishlist$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getSubtitles()` */
  static readonly GetSubtitlesPath = '/store/subtitles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSubtitles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubtitles$Response(params?: GetSubtitles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SubtitleResponse>>> {
    return getSubtitles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSubtitles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSubtitles(params?: GetSubtitles$Params, context?: HttpContext): Observable<Array<SubtitleResponse>> {
    return this.getSubtitles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SubtitleResponse>>): Array<SubtitleResponse> => r.body)
    );
  }

  /** Path part for operation `getAllPlatforms()` */
  static readonly GetAllPlatformsPath = '/store/platforms';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllPlatforms()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlatforms$Response(params?: GetAllPlatforms$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlatformResponse>>> {
    return getAllPlatforms(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllPlatforms$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllPlatforms(params?: GetAllPlatforms$Params, context?: HttpContext): Observable<Array<PlatformResponse>> {
    return this.getAllPlatforms$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PlatformResponse>>): Array<PlatformResponse> => r.body)
    );
  }

  /** Path part for operation `getLanguages()` */
  static readonly GetLanguagesPath = '/store/languages';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLanguages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLanguages$Response(params?: GetLanguages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LanguageResponse>>> {
    return getLanguages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLanguages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLanguages(params?: GetLanguages$Params, context?: HttpContext): Observable<Array<LanguageResponse>> {
    return this.getLanguages$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LanguageResponse>>): Array<LanguageResponse> => r.body)
    );
  }

  /** Path part for operation `getAllGenres()` */
  static readonly GetAllGenresPath = '/store/genres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllGenres()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllGenres$Response(params?: GetAllGenres$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GenreResponse>>> {
    return getAllGenres(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllGenres$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllGenres(params?: GetAllGenres$Params, context?: HttpContext): Observable<Array<GenreResponse>> {
    return this.getAllGenres$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GenreResponse>>): Array<GenreResponse> => r.body)
    );
  }

  /** Path part for operation `getGameById()` */
  static readonly GetGameByIdPath = '/store/game/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGameById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGameById$Response(params: GetGameById$Params, context?: HttpContext): Observable<StrictHttpResponse<GameResponse>> {
    return getGameById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGameById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGameById(params: GetGameById$Params, context?: HttpContext): Observable<GameResponse> {
    return this.getGameById$Response(params, context).pipe(
      map((r: StrictHttpResponse<GameResponse>): GameResponse => r.body)
    );
  }

  /** Path part for operation `checkGameOwned()` */
  static readonly CheckGameOwnedPath = '/store/check/game/{gameId}/owned/';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkGameOwned()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkGameOwned$Response(params: CheckGameOwned$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkGameOwned(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkGameOwned$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkGameOwned(params: CheckGameOwned$Params, context?: HttpContext): Observable<boolean> {
    return this.checkGameOwned$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `checkGameInWishlist()` */
  static readonly CheckGameInWishlistPath = '/store/check/game/wishlist/{gameId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkGameInWishlist()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkGameInWishlist$Response(params: CheckGameInWishlist$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkGameInWishlist(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkGameInWishlist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkGameInWishlist(params: CheckGameInWishlist$Params, context?: HttpContext): Observable<boolean> {
    return this.checkGameInWishlist$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `findAllGames()` */
  static readonly FindAllGamesPath = '/store/all-games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames$Response(params?: FindAllGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return findAllGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllGames(params?: FindAllGames$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.findAllGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

  /** Path part for operation `getAgeRating()` */
  static readonly GetAgeRatingPath = '/store/age-ratings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAgeRating()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAgeRating$Response(params?: GetAgeRating$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AgeRatingResponse>>> {
    return getAgeRating(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAgeRating$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAgeRating(params?: GetAgeRating$Params, context?: HttpContext): Observable<Array<AgeRatingResponse>> {
    return this.getAgeRating$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AgeRatingResponse>>): Array<AgeRatingResponse> => r.body)
    );
  }

}
