/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUnitSizes } from '../fn/system-requirements-controller/get-unit-sizes';
import { GetUnitSizes$Params } from '../fn/system-requirements-controller/get-unit-sizes';
import { UnitSizeResponse } from '../models/unit-size-response';

@Injectable({ providedIn: 'root' })
export class SystemRequirementsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getUnitSizes()` */
  static readonly GetUnitSizesPath = '/system-requirements/unit-sizes';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUnitSizes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnitSizes$Response(params?: GetUnitSizes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UnitSizeResponse>>> {
    return getUnitSizes(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUnitSizes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUnitSizes(params?: GetUnitSizes$Params, context?: HttpContext): Observable<Array<UnitSizeResponse>> {
    return this.getUnitSizes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UnitSizeResponse>>): Array<UnitSizeResponse> => r.body)
    );
  }

}
