/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUserLevelProgress } from '../fn/user-level-controller/get-user-level-progress';
import { GetUserLevelProgress$Params } from '../fn/user-level-controller/get-user-level-progress';
import { LevelProgressResponse } from '../models/level-progress-response';

@Injectable({ providedIn: 'root' })
export class UserLevelControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getUserLevelProgress()` */
  static readonly GetUserLevelProgressPath = '/user-level/user/level-progress';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserLevelProgress()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserLevelProgress$Response(params?: GetUserLevelProgress$Params, context?: HttpContext): Observable<StrictHttpResponse<LevelProgressResponse>> {
    return getUserLevelProgress(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserLevelProgress$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserLevelProgress(params?: GetUserLevelProgress$Params, context?: HttpContext): Observable<LevelProgressResponse> {
    return this.getUserLevelProgress$Response(params, context).pipe(
      map((r: StrictHttpResponse<LevelProgressResponse>): LevelProgressResponse => r.body)
    );
  }

}
