/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUserPrivate } from '../fn/user-profile-controller/get-user-private';
import { GetUserPrivate$Params } from '../fn/user-profile-controller/get-user-private';
import { getUserPublic } from '../fn/user-profile-controller/get-user-public';
import { GetUserPublic$Params } from '../fn/user-profile-controller/get-user-public';
import { setStatusToAway } from '../fn/user-profile-controller/set-status-to-away';
import { SetStatusToAway$Params } from '../fn/user-profile-controller/set-status-to-away';
import { setStatusToOffline } from '../fn/user-profile-controller/set-status-to-offline';
import { SetStatusToOffline$Params } from '../fn/user-profile-controller/set-status-to-offline';
import { setStatusToOnline } from '../fn/user-profile-controller/set-status-to-online';
import { SetStatusToOnline$Params } from '../fn/user-profile-controller/set-status-to-online';
import { updateBio } from '../fn/user-profile-controller/update-bio';
import { UpdateBio$Params } from '../fn/user-profile-controller/update-bio';
import { updateFavoriteGenres } from '../fn/user-profile-controller/update-favorite-genres';
import { UpdateFavoriteGenres$Params } from '../fn/user-profile-controller/update-favorite-genres';
import { updateUserProfile } from '../fn/user-profile-controller/update-user-profile';
import { UpdateUserProfile$Params } from '../fn/user-profile-controller/update-user-profile';
import { uploadBannerImage } from '../fn/user-profile-controller/upload-banner-image';
import { UploadBannerImage$Params } from '../fn/user-profile-controller/upload-banner-image';
import { uploadProfileImage } from '../fn/user-profile-controller/upload-profile-image';
import { UploadProfileImage$Params } from '../fn/user-profile-controller/upload-profile-image';
import { UserPrivateResponse } from '../models/user-private-response';
import { UserPublicResponse } from '../models/user-public-response';

@Injectable({ providedIn: 'root' })
export class UserProfileControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateUserProfile()` */
  static readonly UpdateUserProfilePath = '/profile/update-profile';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUserProfile()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserProfile$Response(params: UpdateUserProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateUserProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUserProfile$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserProfile(params: UpdateUserProfile$Params, context?: HttpContext): Observable<number> {
    return this.updateUserProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `updateBio()` */
  static readonly UpdateBioPath = '/profile/update-bio';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBio()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBio$Response(params: UpdateBio$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return updateBio(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBio$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateBio(params: UpdateBio$Params, context?: HttpContext): Observable<number> {
    return this.updateBio$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `setStatusToOnline()` */
  static readonly SetStatusToOnlinePath = '/profile/status/online';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setStatusToOnline()` instead.
   *
   * This method doesn't expect any request body.
   */
  setStatusToOnline$Response(params?: SetStatusToOnline$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return setStatusToOnline(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setStatusToOnline$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setStatusToOnline(params?: SetStatusToOnline$Params, context?: HttpContext): Observable<void> {
    return this.setStatusToOnline$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setStatusToOffline()` */
  static readonly SetStatusToOfflinePath = '/profile/status/offline';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setStatusToOffline()` instead.
   *
   * This method doesn't expect any request body.
   */
  setStatusToOffline$Response(params?: SetStatusToOffline$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return setStatusToOffline(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setStatusToOffline$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setStatusToOffline(params?: SetStatusToOffline$Params, context?: HttpContext): Observable<void> {
    return this.setStatusToOffline$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setStatusToAway()` */
  static readonly SetStatusToAwayPath = '/profile/status/away';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setStatusToAway()` instead.
   *
   * This method doesn't expect any request body.
   */
  setStatusToAway$Response(params?: SetStatusToAway$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return setStatusToAway(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setStatusToAway$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  setStatusToAway(params?: SetStatusToAway$Params, context?: HttpContext): Observable<void> {
    return this.setStatusToAway$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `uploadProfileImage()` */
  static readonly UploadProfileImagePath = '/profile/image';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadProfileImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProfileImage$Response(params?: UploadProfileImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadProfileImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadProfileImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadProfileImage(params?: UploadProfileImage$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadProfileImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `uploadBannerImage()` */
  static readonly UploadBannerImagePath = '/profile/banner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadBannerImage()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadBannerImage$Response(params?: UploadBannerImage$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return uploadBannerImage(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadBannerImage$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadBannerImage(params?: UploadBannerImage$Params, context?: HttpContext): Observable<{
}> {
    return this.uploadBannerImage$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `updateFavoriteGenres()` */
  static readonly UpdateFavoriteGenresPath = '/profile/add/genres';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateFavoriteGenres()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateFavoriteGenres$Response(params: UpdateFavoriteGenres$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateFavoriteGenres(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateFavoriteGenres$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateFavoriteGenres(params: UpdateFavoriteGenres$Params, context?: HttpContext): Observable<void> {
    return this.updateFavoriteGenres$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUserPublic()` */
  static readonly GetUserPublicPath = '/profile/user/{userId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserPublic()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPublic$Response(params: GetUserPublic$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPublicResponse>> {
    return getUserPublic(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserPublic$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPublic(params: GetUserPublic$Params, context?: HttpContext): Observable<UserPublicResponse> {
    return this.getUserPublic$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserPublicResponse>): UserPublicResponse => r.body)
    );
  }

  /** Path part for operation `getUserPrivate()` */
  static readonly GetUserPrivatePath = '/profile/user/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserPrivate()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPrivate$Response(params?: GetUserPrivate$Params, context?: HttpContext): Observable<StrictHttpResponse<UserPrivateResponse>> {
    return getUserPrivate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserPrivate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserPrivate(params?: GetUserPrivate$Params, context?: HttpContext): Observable<UserPrivateResponse> {
    return this.getUserPrivate$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserPrivateResponse>): UserPrivateResponse => r.body)
    );
  }

}
