/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getWishlist } from '../fn/wishlist-controller/get-wishlist';
import { GetWishlist$Params } from '../fn/wishlist-controller/get-wishlist';
import { PageResponseGameResponse } from '../models/page-response-game-response';

@Injectable({ providedIn: 'root' })
export class WishlistControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getWishlist()` */
  static readonly GetWishlistPath = '/wishlist/wishlist';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWishlist()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWishlist$Response(params?: GetWishlist$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseGameResponse>> {
    return getWishlist(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWishlist$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWishlist(params?: GetWishlist$Params, context?: HttpContext): Observable<PageResponseGameResponse> {
    return this.getWishlist$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseGameResponse>): PageResponseGameResponse => r.body)
    );
  }

}
