/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommunityFlagsResponse } from '../../models/community-flags-response';

export interface GetAllCommunityFlags$Params {
}

export function getAllCommunityFlags(http: HttpClient, rootUrl: string, params?: GetAllCommunityFlags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CommunityFlagsResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllCommunityFlags.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CommunityFlagsResponse>>;
    })
  );
}

getAllCommunityFlags.PATH = '/flags/get/community/flags';
