/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserLibraryResponse } from '../../models/user-library-response';

export interface GetLibraryGameById$Params {
  gameId: number;
}

export function getLibraryGameById(http: HttpClient, rootUrl: string, params: GetLibraryGameById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserLibraryResponse>> {
  const rb = new RequestBuilder(rootUrl, getLibraryGameById.PATH, 'get');
  if (params) {
    rb.path('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserLibraryResponse>;
    })
  );
}

getLibraryGameById.PATH = '/library/game/{gameId}';
