/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseUserLibraryResponse } from '../../models/page-response-user-library-response';

export interface GetDownloadedGames$Params {
  page?: number;
  size?: number;
}

export function getDownloadedGames(http: HttpClient, rootUrl: string, params?: GetDownloadedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserLibraryResponse>> {
  const rb = new RequestBuilder(rootUrl, getDownloadedGames.PATH, 'post');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseUserLibraryResponse>;
    })
  );
}

getDownloadedGames.PATH = '/library/downloaded-games';
