/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseAdminSuspendedAccountsResponse } from '../../models/page-response-admin-suspended-accounts-response';

export interface GetSuspendedAccount$Params {
  page?: number;
}

export function getSuspendedAccount(http: HttpClient, rootUrl: string, params?: GetSuspendedAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseAdminSuspendedAccountsResponse>> {
  const rb = new RequestBuilder(rootUrl, getSuspendedAccount.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseAdminSuspendedAccountsResponse>;
    })
  );
}

getSuspendedAccount.PATH = '/admin/suspended-accounts';
