/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminUserModerationResponse } from '../../models/admin-user-moderation-response';

export interface GetSuspendedUserDetails$Params {
  userId: number;
}

export function getSuspendedUserDetails(http: HttpClient, rootUrl: string, params: GetSuspendedUserDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminUserModerationResponse>> {
  const rb = new RequestBuilder(rootUrl, getSuspendedUserDetails.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminUserModerationResponse>;
    })
  );
}

getSuspendedUserDetails.PATH = '/admin/suspended-user/details/{userId}';
