/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminUserResponse } from '../../models/admin-user-response';

export interface GetUserInfo$Params {
  userId: number;
}

export function getUserInfo(http: HttpClient, rootUrl: string, params: GetUserInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminUserResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserInfo.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminUserResponse>;
    })
  );
}

getUserInfo.PATH = '/admin/user/info/{userId}';
