/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameResponse } from '../../models/game-response';

export interface GetGameInfo$Params {
  gameId: number;
}

export function getGameInfo(http: HttpClient, rootUrl: string, params: GetGameInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<GameResponse>> {
  const rb = new RequestBuilder(rootUrl, getGameInfo.PATH, 'get');
  if (params) {
    rb.path('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameResponse>;
    })
  );
}

getGameInfo.PATH = '/admin/game/info/{gameId}';
