/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountStatusResponse } from '../../models/account-status-response';

export interface GetAllAccountStatuses$Params {
}

export function getAllAccountStatuses(http: HttpClient, rootUrl: string, params?: GetAllAccountStatuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AccountStatusResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllAccountStatuses.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AccountStatusResponse>>;
    })
  );
}

getAllAccountStatuses.PATH = '/admin/account-statuses';
