/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardResponse } from '../../models/dashboard-response';

export interface LoadDashboardData$Params {
  page?: number;
  size?: number;
}

export function loadDashboardData(http: HttpClient, rootUrl: string, params?: LoadDashboardData$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardResponse>> {
  const rb = new RequestBuilder(rootUrl, loadDashboardData.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardResponse>;
    })
  );
}

loadDashboardData.PATH = '/admin/dashboard';
