ALTER TABLE game_hub.game
  ADD COLUMN IF NOT EXISTS has_discount BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS discount_price DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS discount_percent INTEGER;