/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { GameControllerService } from './services/game-controller.service';
import { ReportControllerService } from './services/report-controller.service';
import { UserProfileControllerService } from './services/user-profile-controller.service';
import { LibraryControllerService } from './services/library-controller.service';
import { CommunityControllerService } from './services/community-controller.service';
import { AuthenticationService } from './services/authentication.service';
import { WishlistControllerService } from './services/wishlist-controller.service';
import { UserLevelControllerService } from './services/user-level-controller.service';
import { LocationControllerService } from './services/location-controller.service';
import { FlagsControllerService } from './services/flags-controller.service';
import { CardColorControllerService } from './services/card-color-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    GameControllerService,
    ReportControllerService,
    UserProfileControllerService,
    LibraryControllerService,
    CommunityControllerService,
    AuthenticationService,
    WishlistControllerService,
    UserLevelControllerService,
    LocationControllerService,
    FlagsControllerService,
    CardColorControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
