/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BadgeResponse } from './models/badge-response';
export type { BannerRequest } from './models/banner-request';
export type { ForgotPasswordRequest } from './models/forgot-password-request';
export type { Game } from './models/game';
export type { GameRequest } from './models/game-request';
export type { GameResponse } from './models/game-response';
export type { GameResponseShort } from './models/game-response-short';
export type { Genre } from './models/genre';
export type { GenreResponse } from './models/genre-response';
export type { Language } from './models/language';
export type { LanguageResponse } from './models/language-response';
export type { LocationResponse } from './models/location-response';
export type { PageResponseGameResponse } from './models/page-response-game-response';
export type { Platform } from './models/platform';
export type { PlatformResponse } from './models/platform-response';
export type { RegistrationRequest } from './models/registration-request';
export type { StatusResponse } from './models/status-response';
export type { SubtitleResponse } from './models/subtitle-response';
export type { Subtitles } from './models/subtitles';
export type { SystemRequirements } from './models/system-requirements';
export type { TokenExpiredResponse } from './models/token-expired-response';
export type { UserPrivateResponse } from './models/user-private-response';
export type { UserPublicResponse } from './models/user-public-response';
export type { UserUpdateRequest } from './models/user-update-request';
