/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AgeRating } from './models/age-rating';
export type { AgeratingResponse } from './models/agerating-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BadgeResponse } from './models/badge-response';
export type { BannerRequest } from './models/banner-request';
export type { CardColorResponse } from './models/card-color-response';
export type { FlagsResponse } from './models/flags-response';
export type { ForgotPasswordRequest } from './models/forgot-password-request';
export type { FriendRequestResponse } from './models/friend-request-response';
export type { Game } from './models/game';
export type { GameRequest } from './models/game-request';
export type { GameResponse } from './models/game-response';
export type { GameResponseShort } from './models/game-response-short';
export type { Genre } from './models/genre';
export type { GenreResponse } from './models/genre-response';
export type { Language } from './models/language';
export type { LanguageResponse } from './models/language-response';
export type { LevelProgressResponse } from './models/level-progress-response';
export type { LevelResponse } from './models/level-response';
export type { LocationResponse } from './models/location-response';
export type { PageResponseFriendRequestResponse } from './models/page-response-friend-request-response';
export type { PageResponseGameResponse } from './models/page-response-game-response';
export type { PageResponseUserCommunityResponse } from './models/page-response-user-community-response';
export type { Platform } from './models/platform';
export type { PlatformResponse } from './models/platform-response';
export type { RegistrationRequest } from './models/registration-request';
export type { ReportReasonResponse } from './models/report-reason-response';
export type { ReportRequest } from './models/report-request';
export type { StatusResponse } from './models/status-response';
export type { StoreFlagsResponse } from './models/store-flags-response';
export type { SubtitleResponse } from './models/subtitle-response';
export type { Subtitles } from './models/subtitles';
export type { SystemRequirements } from './models/system-requirements';
export type { TokenExpiredResponse } from './models/token-expired-response';
export type { UserCommunityResponse } from './models/user-community-response';
export type { UserPrivateResponse } from './models/user-private-response';
export type { UserPublicResponse } from './models/user-public-response';
export type { UserUpdateRequest } from './models/user-update-request';
