/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegionResponse } from '../../models/region-response';

export interface GetAllRegions$Params {
}

export function getAllRegions(http: HttpClient, rootUrl: string, params?: GetAllRegions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RegionResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllRegions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RegionResponse>>;
    })
  );
}

getAllRegions.PATH = '/find-players/regions';
