/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlatformResponse } from '../../models/platform-response';

export interface GetAllGamingPlatforms$Params {
}

export function getAllGamingPlatforms(http: HttpClient, rootUrl: string, params?: GetAllGamingPlatforms$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlatformResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllGamingPlatforms.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlatformResponse>>;
    })
  );
}

getAllGamingPlatforms.PATH = '/find-players/gaming-platforms';
