/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LevelProgressResponse } from '../../models/level-progress-response';

export interface GetUserLevelProgress$Params {
}

export function getUserLevelProgress(http: HttpClient, rootUrl: string, params?: GetUserLevelProgress$Params, context?: HttpContext): Observable<StrictHttpResponse<LevelProgressResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserLevelProgress.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LevelProgressResponse>;
    })
  );
}

getUserLevelProgress.PATH = '/user-level/user/level-progress';
