/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseWishlistResponse } from '../../models/page-response-wishlist-response';

export interface GetWishlist$Params {
  page?: number;
  size?: number;
  genre?: string;
  operationSystem?: string;
  discount?: boolean;
  sortBy?: string;
}

export function getWishlist(http: HttpClient, rootUrl: string, params?: GetWishlist$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseWishlistResponse>> {
  const rb = new RequestBuilder(rootUrl, getWishlist.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('genre', params.genre, {});
    rb.query('operationSystem', params.operationSystem, {});
    rb.query('discount', params.discount, {});
    rb.query('sortBy', params.sortBy, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseWishlistResponse>;
    })
  );
}

getWishlist.PATH = '/wishlist/wishlist';
